accounts:

# a*****87@protonmail.com

blockchainExplorer:
  bsc:
    key: 'MB1EM53BDJFKDIHUZ5JJT946BJJUQIHFP2'
    host: 'https://api.bscscan.com'
    www: 'https://bscscan.com'
  eth:
    key: 'FGCTXVXMZAPPW91KCZ91AMZFGBY1GZZB51'
    host: 'https://api.etherscan.io'
    www: 'https://etherscan.io'
  eth:goerli:
    host: 'https://api-goerli.etherscan.io'
    www: 'https://goerli.etherscan.io'
  polygon:
    key: 'AQHXXI3KIU5FC8Y1WXX8A346PENKUX7BCE'
    host: 'https://api.polygonscan.com'
    www: 'https://polygonscan.com'
  xdai:
    key: ''
    host: 'https://blockscout.com/xdai/mainnet'
    www: 'https://blockscout.com/xdai/mainnet'
  celo:
    key: '3A9ZR89MEUQ51YC3SI1VAYAATFW419EEYR'
    host: 'https://api.celoscan.io'
    www: 'https://celoscan.io'

web3:
  eth:
    endpoints:
      - url: 'https://mainnet.infura.io/v3/e38914b4ccbc4a60a71a1d6a336bc00f'
      - url: 'wss://mainnet.infura.io/ws/v3/e38914b4ccbc4a60a71a1d6a336bc00f'

  eth:goerli:
    endpoints:
      - url: 'https://goerli.infura.io/v3/e38914b4ccbc4a60a71a1d6a336bc00f'
      - url: 'wss://goerli.infura.io/ws/v3/e38914b4ccbc4a60a71a1d6a336bc00f'

  # semi-private accounts at https://rpc.maticvigil.com/
  polygon:
    endpoints:
      - url: 'https://rpc-mainnet.maticvigil.com/v1/d41908ce4587e7646e975270498ce8da070112a2'
      - url: 'wss://rpc-mainnet.maticvigil.com/ws/v1/d41908ce4587e7646e975270498ce8da070112a2'

  # from https://docs.binance.org/smart-chain/developer/rpc.html
  bsc:
    endpoints:
      - url: 'https://bsc-dataseed.binance.org/'
      - url: 'https://bsc-dataseed1.defibit.io/'
      - url: 'wss://bsc-ws-node.nariox.org:443'

  xdai:
    endpoints:
      - url: 'https://rpc.gnosischain.com/'

  hardhat:
    endpoints:
      - url: 'http://127.0.0.1:8545/'

  celo:
    chainId: 42220
    chainToken: CELO
    endpoints:
      - url: 'https://forno.celo.org'
      - url: 'wss://forno.celo.org/ws'


ns:
  ens:
    registry: '0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e'
  ud:
    # https://docs.unstoppabledomains.com/send-and-receive-crypto-payments/direct-blockchain-calls/resolve-unstoppable-domain-names
    eth:
      registry: '0xfee4d4f0adff8d84c12170306507554bc7045878'
    polygon:
      registry: '0xa3f32c8cd786dc089bd1fc175f2707223aee5d00'
