accounts:

# a*****87@protonmail.com

blockchainExplorer:
  bsc:
    key: 'MB1EM53BDJFKDIHUZ5JJT946BJJUQIHFP2'
    host: 'https://api.bscscan.com'
    www: 'https://bscscan.com'
  eth:
    key: 'FGCTXVXMZAPPW91KCZ91AMZFGBY1GZZB51'
    host: 'https://api.etherscan.io'
    www: 'https://etherscan.io'
  eth:goerli:
    host: 'https://api-goerli.etherscan.io'
    www: 'https://goerli.etherscan.io'
  polygon:
    key: 'AQHXXI3KIU5FC8Y1WXX8A346PENKUX7BCE'
    host: 'https://api.polygonscan.com'
    www: 'https://polygonscan.com'
  polygon:mumbai:
    key: 'AQHXXI3KIU5FC8Y1WXX8A346PENKUX7BCE'
    host: 'https://api-testnet.polygonscan.com'
    www: 'https://mumbai.polygonscan.com'

  xdai:
    key: ''
    host: 'https://blockscout.com/xdai/mainnet'
    www: 'https://blockscout.com/xdai/mainnet'
  gnosis:
    key: 'V6ENPXHS2E74MCBUXWG8WGYTA3ZPYN2WT3'
    host: 'https://api.gnosisscan.io/'
    www: 'https://gnosisscan.io'
  celo:
    key: '3A9ZR89MEUQ51YC3SI1VAYAATFW419EEYR'
    host: 'https://api.celoscan.io'
    www: 'https://celoscan.io'
  heco:
    key: '...'
    host: 'https://api.hecoinfo.com'
    www: 'https://www.hecoinfo.com'
  optimism:
    key: '8SG776V5FEBDJMHTMETG3PT6KT1921X6AS'
    host: 'https://api-optimistic.etherscan.io'
    www: 'https://optimistic.etherscan.io'
  avalanche:
    key: 'TMEXUDTD37PNTAIDJACPHQTP5BB42XD8Q3'
    host: 'https://api.snowtrace.io'
    www: 'https://snowtrace.io'
  cronos:
    key: 'V5A6VRJ5TR9KIQEI7HIHVGK5C9NYCQS36E'
    host: 'https://api.cronoscan.com'
    www: 'https://cronoscan.com'
  fantom:
    key: '9PFA8WNHPCRAZS2GEJXPNN83SZS84JWGG7'
    host: 'https://api.ftmscan.com'
    www: 'https://ftmscan.com'
  aurora:
    key: ''
    host: 'https://explorer.aurora.dev'
    www: 'https://explorer.aurora.dev'
  arbitrum:
    key: 'SD1353XFNU8QYTP4KDK58AHMZBQCE79Q1J'
    host: 'https://api.arbiscan.io'
    www: 'https://arbiscan.io'
  metis:
    key: ''
    host: 'https://andromeda-explorer.metis.io/api'
    www: 'https://andromeda-explorer.metis.io'

web3:
  eth:
    endpoints:
      # public rpc (ankr, linkpool)
      - url: 'https://eth.public-rpc.com'
      - url: 'https://main-light.eth.linkpool.io'
        rateLimit: 2000/5m
      - url: 'wss://main-light.eth.linkpool.io/ws'
        rateLimit: 2000/5m
      # custom infura
      - url: 'https://mainnet.infura.io/v3/a83f91c556054576a4c608ad4312720b'
        rateLimit: 100/1s;5000/1m
      - url: 'wss://mainnet.infura.io/ws/v3/a83f91c556054576a4c608ad4312720b'

  eth:goerli:
    endpoints:
      - url: 'https://goerli.infura.io/v3/a83f91c556054576a4c608ad4312720b'
      - url: 'wss://goerli.infura.io/ws/v3/a83f91c556054576a4c608ad4312720b'

  # semi-private accounts at https://rpc.maticvigil.com/
  polygon:
    endpoints:
      - url: 'https://polygon-rpc.com'
      #- url: 'https://rpc-mainnet.maticvigil.com/v1/d41908ce4587e7646e975270498ce8da070112a2'
      #- url: 'wss://rpc-mainnet.maticvigil.com/ws/v1/d41908ce4587e7646e975270498ce8da070112a2'

  polygon:mumbai:
    chainId: 80001
    endpoints:
      - url: 'https://rpc-mumbai.maticvigil.com'

  # from https://docs.binance.org/smart-chain/developer/rpc.html
  bsc:
    endpoints:
      - url: 'https://bscrpc.com'
      - url: 'https://bsc-dataseed.binance.org/'
      - url: 'https://bsc-dataseed1.defibit.io/'
      - url: 'wss://bsc-ws-node.nariox.org:443'

  xdai:
    endpoints:
      - url: 'https://rpc.gnosischain.com/'
      - url: 'wss://rpc.gnosischain.com/wss'

  gnosis:
    chainId: 100
    chainToken: xDAI
    endpoints:
      - url: 'https://rpc.gnosischain.com/'
      - url: 'wss://rpc.gnosischain.com/wss'

  arbitrum:
    chainId: 42161
    endpoints:
      - url: 'https://arbitrum.public-rpc.com'

  optimism:
    chainId: 10
    endpoints:
      - url: 'https://mainnet.optimism.io'

  avalanche:
    chainId: 43114
    chainToken: AVAX
    endpoints:
      - url: 'https://avalanche-evm.publicnode.com'
      - url: 'https://api.avax.network/ext/bc/C/rpc'

  cronos:
    chainId: 25
    chainToken: CRO
    endpoints:
      - url: https://evm.cronos.org

  hardhat:
    endpoints:
      - url: 'http://127.0.0.1:8545/'

  celo:
    chainId: 42220
    chainToken: CELO
    endpoints:
      - url: 'https://forno.celo.org'
      - url: 'wss://forno.celo.org/ws'

  heco:
    chainId: 128
    chainToken: HT
    endpoints:
      - url: 'https://http-mainnet.hecochain.com'
      - url: 'wss://ws-mainnet.hecochain.com'

  fantom:
    chainId: 250
    chainToken: FTM
    endpoints:
      - url: 'https://rpc.fantom.network'
      - url: 'https://rpcapi.fantom.network'

  aurora:
    chainId: 1313161554
    endpoints:
      - url: 'https://mainnet.aurora.dev'

  metis:
    chainId: 1088
    chainToken: METIS
    endpoints:
      - url: https://andromeda.metis.io/?owner=1088

ns:
  ens:
    registry: '0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e'
  ud:
    # https://docs.unstoppabledomains.com/send-and-receive-crypto-payments/direct-blockchain-calls/resolve-unstoppable-domain-names
    eth:
      registry: '0xfee4d4f0adff8d84c12170306507554bc7045878'
    polygon:
      registry: '0xa3f32c8cd786dc089bd1fc175f2707223aee5d00'


oracles:
  coingecko:
    root: https://api.coingecko.com/api/v3
    key:


# https://4337.blocknative.com
erc4337:
    - name: default
      contracts:
        entryPoint: '0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789'
        accountFactory: '0x09c58cf6be8e25560d479bd52b4417d15bca2845'
      platforms:
        - eth
        - eth:goerli
        - polygon
        - polygon:mumbai
