accounts:
  eth:
    - address: ''
      key: ''

# a*****87@protonmail.com

blockchainExplorer:
  bsc:
    key: 'MB1EM53BDJFKDIHUZ5JJT946BJJUQIHFP2'
    host: 'https://api.bscscan.com'
  eth:
    key: 'FGCTXVXMZAPPW91KCZ91AMZFGBY1GZZB51'
    host: 'https://api.etherscan.io'
  polygon:
    key: 'AQHXXI3KIU5FC8Y1WXX8A346PENKUX7BCE'
    host: 'https://api.polygonscan.com'
  xdai:
    key: ''
    host: 'https://blockscout.com/xdai/mainnet'

web3:
  eth:
    endpoints:
      - url: 'https://mainnet.infura.io/v3/e38914b4ccbc4a60a71a1d6a336bc00f'
      - url: 'wss://mainnet.infura.io/ws/v3/e38914b4ccbc4a60a71a1d6a336bc00f'

  # semi-private accounts at https://rpc.maticvigil.com/
  polygon:
    endpoints:
      - url: 'https://rpc-mainnet.maticvigil.com/v1/d41908ce4587e7646e975270498ce8da070112a2'
      - url: 'wss://rpc-mainnet.maticvigil.com/ws/v1/d41908ce4587e7646e975270498ce8da070112a2'

  # from https://docs.binance.org/smart-chain/developer/rpc.html
  bsc:
    endpoints:
      - url: 'https://bsc-dataseed.binance.org/'
      - url: 'https://bsc-dataseed1.defibit.io/'
      - url: 'wss://bsc-ws-node.nariox.org:443'

  xdai:
    endpoints:
      - url: 'https://rpc.gnosischain.com/'
